### ISSUE TITLE
Returned language should match with the one the user prefers

### ISSUE THREAD

**Issue by mt-kenny** [SeregPie/detectNearestLocale#1]
```
const locale = detectNearestLocale(['en', 'ja', 'en-AU'], ["en-IN", "ja", "en-UK"]);
// returns 'ja' but expected 'en'
```
As you can see in this example, the language doesn't return English as expected. Instead of looking for exact match, it would be nice if we could get the language the user actually understand.

**Comment by SeregPie** [comment]
it returns `ja`, because it is an exact match. in your example the user speaks two dialect english languages and japanese. the supported languages are a different dialect english, japanese and general english.
